-- share_link_rpc.sql
-- Adds a SECURITY DEFINER RPC `public.get_shared_project_data(p_token, p_user_agent)`
-- that consolidates share-link validation (active + not expired + email allowlist)
-- and returns a curated project + sessions projection in a single round-trip.
--
-- Closes audit findings:
--   • Critical #1 — email allowlist now enforced server-side
--   • Critical #2 — expiration enforced inside the database, not JS
--   • High     #4 — anon SELECT on `projects` / `pomodoro_sessions` no longer needed;
--                   `user_id` is never returned to the client
--
-- Also tightens `project_shares.access_type` to `'read-only'` so the dead UI
-- options ('comment', 'edit') cannot be persisted (audit High #5).
--
-- Run order : AFTER `create_project_sharing.sql`
-- Safe to re-run: YES (idempotent)


-- ============================================================
-- 1. Tighten `project_shares.access_type` CHECK constraint
-- ============================================================
-- Migrate any existing rows out of 'comment' / 'edit' (the backend never
-- enforced those modes — they were always read-only in practice), drop the
-- old constraint, and re-add a stricter one. Idempotent.

DO $$
DECLARE
  v_constraint_def TEXT;
BEGIN
  -- Coerce legacy rows to the only supported mode.
  UPDATE project_shares
     SET access_type = 'read-only'
   WHERE access_type <> 'read-only';

  -- The original constraint name is auto-generated by Postgres
  -- (project_shares_access_type_check). Drop whatever check is there.
  ALTER TABLE project_shares
    DROP CONSTRAINT IF EXISTS project_shares_access_type_check;

  -- Re-create with the tightened predicate.
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conname = 'project_shares_access_type_check'
       AND conrelid = 'public.project_shares'::regclass
  ) THEN
    ALTER TABLE project_shares
      ADD CONSTRAINT project_shares_access_type_check
      CHECK (access_type = 'read-only');
  END IF;
END $$;


-- ============================================================
-- 2. RPC: get_shared_project_data
-- ============================================================
-- Validates the token and returns { project, sessions, share_info } as JSONB.
-- Raises one of three sentinel exceptions on failure so the JS hook can map
-- them to UI states:
--
--   INVALID_OR_EXPIRED — token unknown, inactive, or past its expires_at
--   AUTH_REQUIRED      — share has shared_with_email set, but caller is anon
--   EMAIL_MISMATCH     — share has shared_with_email set, caller is signed in
--                        but with a different email
--
-- The RPC also records a project_share_views row, which fires the existing
-- increment_share_view_count trigger to keep `view_count` in sync. That work
-- happens with DEFINER privileges, so it does not require the anon-INSERT
-- policy on project_share_views to remain in place.

CREATE OR REPLACE FUNCTION public.get_shared_project_data(
  p_token      TEXT,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_share        project_shares%ROWTYPE;
  v_caller_email TEXT;
  v_result       JSONB;
BEGIN
  -- 1. Look up the share by token, restricted to active + not-expired.
  --    All three flags are enforced in SQL; no JS-side check is trusted.
  SELECT *
    INTO v_share
    FROM project_shares
   WHERE share_token = p_token
     AND is_active = TRUE
     AND (expires_at IS NULL OR expires_at > NOW());

  IF NOT FOUND THEN
    RAISE EXCEPTION 'INVALID_OR_EXPIRED';
  END IF;

  -- 2. If the share is email-restricted, require auth + matching email.
  IF v_share.shared_with_email IS NOT NULL THEN
    IF auth.uid() IS NULL THEN
      RAISE EXCEPTION 'AUTH_REQUIRED';
    END IF;

    SELECT email
      INTO v_caller_email
      FROM auth.users
     WHERE id = auth.uid();

    IF v_caller_email IS NULL
       OR lower(v_caller_email) <> lower(v_share.shared_with_email) THEN
      RAISE EXCEPTION 'EMAIL_MISMATCH';
    END IF;
  END IF;

  -- 3. Build the curated projection. `user_id` is intentionally omitted from
  --    every row so the response cannot be used to enumerate accounts.
  SELECT jsonb_build_object(
    'project', (
      SELECT jsonb_build_object(
        'id',          p.id,
        'name',        p.name,
        'description', p.description,
        'color',       p.color,
        'hourly_rate', p.hourly_rate,
        'created_at',  p.created_at
      )
      FROM projects p
      WHERE p.id = v_share.project_id
    ),
    'sessions', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id',               s.id,
          'started_at',       s.started_at,
          'duration_minutes', s.duration_minutes,
          'description',      s.description,
          'tags',             s.tags
        )
        ORDER BY s.started_at DESC
      )
      FROM (
        SELECT id, started_at, duration_minutes, description, tags
          FROM pomodoro_sessions
         WHERE project_id = v_share.project_id
           AND mode = 'focus'
         ORDER BY started_at DESC
         LIMIT 50
      ) s
    ), '[]'::jsonb),
    'share_info', jsonb_build_object(
      'id',                v_share.id,
      'label',             v_share.label,
      'access_type',       v_share.access_type,
      'expires_at',        v_share.expires_at,
      'shared_with_email', v_share.shared_with_email
    )
  )
  INTO v_result;

  -- 4. Record the view for analytics. The increment_share_view_count trigger
  --    bumps project_shares.view_count + last_accessed_at automatically.
  INSERT INTO project_share_views (share_id, viewer_user_agent)
  VALUES (v_share.id, p_user_agent);

  RETURN v_result;
END;
$$;

REVOKE ALL    ON FUNCTION public.get_shared_project_data(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_shared_project_data(TEXT, TEXT) TO anon, authenticated;

COMMENT ON FUNCTION public.get_shared_project_data(TEXT, TEXT) IS
  'Returns curated project + sessions for a valid share token. '
  'Enforces active/expiry/email-allowlist server-side. '
  'Sentinels: INVALID_OR_EXPIRED, AUTH_REQUIRED, EMAIL_MISMATCH.';
